printWidth = 80
singleQuote = true
tabWidth = 4
trailingComma = 'all'
semi = true
useTabs = true

[[overrides]]
  files = '*.js'
  [overrides.options]
    trailingComma = 'es5'

[[overrides]]
  files = '*.{yml,yaml}'
  [overrides.options]
    tabWidth = 2
